import './PrivacyPage.css'

export default function PrivacyPage({ onClose }) {
  return (
    <div className="privacy-modal-backdrop" role="presentation">
      <article
        className="privacy-page privacy-modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby="privacy-policy-title"
      >
      <header className="privacy-hero">
        <button className="privacy-close-button" type="button" onClick={onClose} aria-label="Close privacy policy">
          ×
        </button>
        <span className="privacy-eyebrow">Privacy</span>
        <h1 id="privacy-policy-title">Privacy and cookie policy</h1>
        <p>
          Last Updated: July 18, 2026
        </p>
      </header>

      <div className="privacy-content">
        <section>
          <h2>1. Introduction</h2>
          <p>
            Welcome to Truth Bubble AI, a product of Tabutech Labs. We are committed to maintaining
            your trust and protecting your privacy. This policy explains how we collect, use, and
            safeguard personal information as you interact with our AI services. In the landscape
            of 2026, we prioritize “radical transparency,” ensuring you understand how our AI
            systems process your data.
          </p>
        </section>

        <section>
          <h2>2. Information We Collect</h2>
          <p>To provide and improve our services, we process the following categories of data:</p>
          <ul>
            <li><strong>User Inputs:</strong> Any text, prompts, queries, or media you upload to the platform.</li>
            <li><strong>Account Information:</strong> Name, email address, and authentication credentials for registered users.</li>
            <li><strong>Usage &amp; Interaction Data:</strong> Metadata regarding how you interact with our AI, including timestamps, feature frequency, and performance metrics.</li>
            <li><strong>Technical Data:</strong> IP addresses, browser types, device identifiers, and log files.</li>
            <li><strong>Inferred Data:</strong> Insights or summaries generated by the AI based on your interactions.</li>
          </ul>
        </section>

        <section>
          <h2>3. How We Use Your Data</h2>
          <p>We process your data for the following purposes:</p>
          <ul>
            <li><strong>Service Provision:</strong> To respond to your queries and operate our AI-powered features.</li>
            <li><strong>Model Improvement:</strong> To refine, develop, and fine-tune our AI models. Users may opt out of training through their privacy settings.</li>
            <li><strong>Security &amp; Safety:</strong> To detect abuse, prevent fraud, and ensure the integrity of our infrastructure.</li>
            <li><strong>Compliance:</strong> To meet legal obligations, including transparency labeling requirements for AI-generated content.</li>
          </ul>
        </section>

        <section>
          <h2>4. AI Transparency &amp; Automated Decision-Making</h2>
          <ul>
            <li><strong>Transparency:</strong> Truth Bubble AI ensures that all AI-generated content is clearly labeled in compliance with 2026 transparency regulations.</li>
            <li><strong>Interaction Awareness:</strong> Our systems are designed to ensure you are aware when you are interacting with an AI.</li>
            <li><strong>Automated Decisions:</strong> Where our AI performs automated decision-making that affects your experience, you have the right to request information about the logic involved and, where applicable, request human review of the outcome.</li>
          </ul>
        </section>

        <section>
          <h2>5. Data Sharing &amp; Third Parties</h2>
          <p>We do not sell your personal data. We share information only under these conditions:</p>
          <ul>
            <li><strong>Essential Service Providers:</strong> With vendors, such as cloud hosting, security, and analytics partners, who are strictly bound by confidentiality and security obligations.</li>
            <li><strong>Legal Requirements:</strong> To comply with law enforcement requests, court orders, or applicable regulations.</li>
          </ul>
        </section>

        <section>
          <h2>6. Your Rights</h2>
          <p>Depending on your jurisdiction, including GDPR and DPDPA, you may have the right to:</p>
          <ul>
            <li><strong>Access &amp; Portability:</strong> Request a copy of your personal data.</li>
            <li><strong>Correction:</strong> Update or rectify inaccurate information.</li>
            <li><strong>Deletion:</strong> Request the permanent removal of your data (“Right to be Forgotten”).</li>
            <li><strong>Object/Opt-Out:</strong> Withdraw consent or object to the use of your data for model training or profiling.</li>
          </ul>
        </section>

        <section>
          <h2>7. Data Retention &amp; Security</h2>
          <p>
            We retain personal data only for as long as necessary to fulfill the purposes outlined
            in this policy. We employ industry-standard security measures, including encryption,
            access controls, and regular audit logging of system interactions. We do not store
            prompts longer than necessary for operational requirements.
          </p>
        </section>

        <section>
          <h2>8. Children’s Privacy</h2>
          <p>
            Truth Bubble AI is not directed at children under the age of 13. We do not knowingly
            collect personal data from minors. If you believe we have inadvertently done so,
            please contact us immediately so we can securely delete the information.
          </p>
        </section>

        <section>
          <h2>9. Cookie Settings</h2>
          <p>
            You can accept or deny optional cookies and reopen the consent menu at any time using
            the button below. Essential browser storage remembers your consent choice.
          </p>
        </section>

        <section>
          <h2>10. Contact Us</h2>
          <p>
            For privacy-related inquiries, requests to exercise your data rights, or to reach our
            Data Protection team, please contact:
          </p>
          <address className="privacy-contact">
            <strong>Tabutech Labs Privacy Office</strong>
            <span>Email: <a href="mailto:tanmaidewan@gmail.com">tanmaidewan@gmail.com</a></span>
            <span>Address: 2991, Street R.B Shiva Sahaimal, Ballimaran, Delhi 110006</span>
            <span>Contact: <a href="tel:+918860706691">+91 8860706691</a></span>
          </address>
        </section>
      </div>
      <div className="privacy-modal-footer">
        <button className="privacy-settings-button" type="button" onClick={onClose}>
          Close policy
        </button>
      </div>
      </article>
    </div>
  )
}
